### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by binarybucks** [dirkmoors/MqttService#1]
Hi, 

it would be great, if you could provide a license with your project. 
I'd really like to include your service in a project as a superior replacement for my own wrapper around the Paho library, but I'm unsure about the licensing of your code.

**Comment by dirkmoors** [comment]
Hi Alexander,

I've added the (MIT) licence, so feel free to use the library. If you have smart ideas/bugfixes or other, just create a pull request!
And if you know any other interest developers or contributors, feel free to encourage them in using the library!

Best regards,
Dirk

**Comment by binarybucks** [comment]
Great, thanks :)
