### ISSUE TITLE
On Disconnection, it does not reconnect

### ISSUE THREAD

**Issue by EurigJones** [dirkmoors/MqttService#3]
I noticed in the code that you replaced the original code (Dale Lane's implementation) with code which attempts to reconnect in another thread. You also commented this out so now it's not reconnecting.

What are the reasons behind this, and what should be happening do you think?

Thanks!

**Comment by binarybucks** [comment]
I was wondering the same.
Also you might want to reset the ConnectionStatus to INITIAL if you set the status to USERDISCONNECT before as discussed in issue #2

**Comment by EurigJones** [comment]
@binarybucks In my project I personally don't have the user disconnecting/connecting manually.

**Comment by dirkmoors** [comment]
@Amorgos That must be a bug, I don't have time right now to fix and test it, but I remember that calling "doStart(final Intent intent, final int startId)" will reconnect, using the selected executor (so potentially in a new thread). Feel free to test/tweak and submit a pull request! 
Also, the user does not have to disconnect/connect manually, I created the handlers so you can bind the connecting/disconnecting to the Activity lifecycle handlers (like onCreate or onDestroy)

**Comment by dirkmoors** [comment]
@binarybucks Can you submit a pull request for that one? Thanks in advance!

**Comment by EurigJones** [comment]
Well I've replaced the commented out call to your reconnectInNewThread() method and replaced it with what Dale Lane's implementation had instead...

```
// try to reconnect
// reconnectInNewThread();
if (connectToBroker())
{
    onConnect();
}
```

It seems to be working, but I guess my original question was if you remember why you weren't happy with the above code?

**Comment by dirkmoors** [comment]
@Amorgos I think the problem with that code was the fact that I needed it to run in a new thread, and perform more status checks before reconnecting. 

When I start to think about it, @binarybucks that's also the reason why I keep the status to USERDISCONNECT. Otherwise when you manually disconnect, the service would try to reconnect.

```
synchronized void handleStart(Intent intent, int startId) 
{
    LOG.debug("handleStart");
    // before we start - check for a couple of reasons why we should stop

    if (mqttClient == null) 
    {
        // we were unable to define the MQTT client connection, so we stop 
        //  immediately - there is nothing that we can do
        LOG.debug("handleStart: mqttClient == null");
        stopSelf();
        return;
    }

    if (connectionStatus == ConnectionStatus.NOTCONNECTED_USERDISCONNECT) {
        // When calling startService in multiple activities, onStartCommand()
        // is called when activies are switched. Thus the service would connect
        // automatically even though the user might have requested the disconnect. 
        return;
    }
```

That keeps a manually disconnected service from auto-reconnecting.
