### ISSUE TITLE
Why is the sending of Ping messages at topic level necessary?

### ISSUE THREAD

**Issue by binarybucks** [dirkmoors/MqttService#4]
Hey, 

while we're at asking questions, I've wondered if it is really necessary to publish Ping messages, as the underlying Paho library already implements native MQTT PINGREQ and PINGRESP handling to keep the connection alive? 

If so, why do we need it?

**Comment by dirkmoors** [comment]
Hi,

The ping implementation is based on the Android Alarmmanager service, which is necessary because the Android OS will generally stop processing you app while it is not being used by the user. Using the Alarmmanager makes sure that the OS will trigger your (potentially sleeping) app, to keep the connection alive.
A use case would be a scenario where the Mqtt connection needs to be open to receive data from a server, even when the app is in the background.
The Paho "ping" implementation would not work reliably on Android, since the OS could put the entire app to sleep, rendering the Paho "ping" inoperable.

**Comment by dirkmoors** [comment]
Thinking about it, it could make sense to use the "native mqtt implementation's" (in this case "Paho") Ping message in favor of my implementation, while still using the Alarmmanager to schedule the ping.
Would that be a better implementation in your opinion?

**Comment by binarybucks** [comment]
It certainly would be. I'll look into it this evening and submit a
pull-request.
Am 22.02.2013 10:38 schrieb "dirkmoors" notifications@github.com:

**Comment by dirkmoors** [comment]
Okay great, looking forward to it!

**Comment by binarybucks** [comment]
So I dug a bit into the depths of Paho and apparently there is no way to manually send a MqttPingReq without hacking the public interfaces.

On the Paho-Dev Mailinglist there is this quote by Nick Oleary:  "The client handles the PINGREQ internally - there is nothing you have to do to trigger a PINGREQ to be sent". It, however, does not mention that there also isn't anything one can do to trigger a PINGREQ to be sent. 

The whole internal client works roughly by checking if there is any work to do. If there is a message that should be handled, it is send. If there is nothing to be done, it is checked if any message went across the wire in the keepalive period. If not, a PINGREQ message is send to keep the connection alive. 

I guess it is not really worth the effort to maintain a modified version of the Paho library just to send propper pings though. What do you thing @dirkmoors?

**Comment by dirkmoors** [comment]
In that case, I would keep using my ping implementation. Maintaining a custom Paho lib would indeed not be worth the effort, and my implementation works just fine. Unless you've got other thoughts, I'm going to close this thread?

**Comment by binarybucks** [comment]
Allright.

**Comment by chinesejie** [comment]
There is a way to send MqttPingReq at any time. See https://github.com/chinesejie/paho-for-android

**Comment by binarybucks** [comment]
Of course this is possible with a modified version of Paho. The question is, is it worth the effort to modify _every_ new version of Paho to include your changes? Besides that, the current implementation with topic level pings works well and does not require any changes to the Paho code, so why change that?

**Comment by chinesejie** [comment]
Em. I have tested the code.  the current implementation with topic level pings at least need send 7 or 8 bytes to the server. While the heartbeat of MQTT is only 2 bytes. I think publishing topic as ping has lost the best advantage of MQTT.

**Comment by binarybucks** [comment]
Sure, but I'm not going to maintain a Paho fork for this, are you? The
correct approach for this is to file an issue with Paho and have it
implemented directly in the official code.

Mit freundlichen Grüßen / With kind regards
Alexander Rust
--Sent from mobile
